# Generated by Django 4.0.3 on 2022-05-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('parent_folder', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folder', to='file.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('user_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extension', models.CharField(max_length=20)),
                ('uuid_file_name', models.CharField(max_length=32)),
                ('parent', models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='child_file', to='file.folder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
